### ISSUE TITLE
Contribute my cyber bully classification web-app

### ISSUE THREAD

**Issue by mohd-raza** [muhammadanas0716/Machine-Learning-101#69]
**What is the awesome project you're thinking of?*
Cyber-Bully Tweet Classification Web-App

**Comment by mohd-raza** [comment]
@muhammadanas0716 hey brother can you assign me this issue, I want to contribute to this project

**Comment by muhammadanas0716** [comment]
Sure thing!

**Comment by muhammadanas0716** [comment]
I have assigned it to you! Please sent a PR once you're done!

**Comment by mohd-raza** [comment]
Thanks

**Comment by muhammadanas0716** [comment]
Project Completed.
